# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('order', models.IntegerField()),
                ('sentBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageFrom', to=settings.AUTH_USER_MODEL)),
                ('sentTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageTo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shirtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirtImg', models.CharField(blank=True, max_length=1000, null=True)),
                ('year', models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, max_length=4, verbose_name='year')),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirtCount', models.IntegerField(blank=True, null=True)),
                ('wanted', models.CommaSeparatedIntegerField(blank=True, max_length=200, null=True)),
                ('post', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.teamProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='shirtimage',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.teamProfile'),
        ),
    ]
