# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20161219_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shirtCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shirtImg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
